const Data =[
    {
        id:1,
        title:'Item-Name',
        description:'Description',
        cost:'cost',
    },
    {
        id:2,
        title:'Item-Name',
        description:'Description',
        cost:'cost',
    },
    {
        id:3,
        title:'Item-Name',
        description:'Description',
        cost:'cost',
    },
    {
        id:4,
        title:'Item-Name',
        description:'Description',
        cost:'cost',
    },
    {
        id:5,
        title:'Item-Name',
        description:'Description',
        cost:'cost',
    },
    {
        id:6,
        title:'Item-Name',
        description:'Description',
        cost:'cost',
    },
]
export default Data;